@startuml OpenApi diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!theme blueprint
title Browse API v1.16.0
footer OpenApi diagram - futurum.openapi-to-plantuml
Container_Boundary(item_summary_search, "/item_summary/search") {
Component(item_summary_search_get, "search", "REST ApiEndpoint - GET", "")

}

Container_Boundary(item_summary_search_by_image, "/item_summary/search_by_image") {
Component(item_summary_search_by_image_post, "searchByImage", "REST ApiEndpoint - POST", "")

}

Container_Boundary(item_item_id, "/item/{item_id}") {
Component(item_item_id_get, "getItem", "REST ApiEndpoint - GET", "")

}

Container_Boundary(item_get_item_by_legacy_id, "/item/get_item_by_legacy_id") {
Component(item_get_item_by_legacy_id_get, "getItemByLegacyId", "REST ApiEndpoint - GET", "")

}

Container_Boundary(item_, "/item/") {
Component(item__get, "getItems", "REST ApiEndpoint - GET", "")

}

Container_Boundary(item_get_items_by_item_group, "/item/get_items_by_item_group") {
Component(item_get_items_by_item_group_get, "getItemsByItemGroup", "REST ApiEndpoint - GET", "")

}

Container_Boundary(item_item_id_check_compatibility, "/item/{item_id}/check_compatibility") {
Component(item_item_id_check_compatibility_post, "checkCompatibility", "REST ApiEndpoint - POST", "")

}

Container_Boundary(shopping_cart_add_item, "/shopping_cart/add_item") {
Component(shopping_cart_add_item_post, "addItem", "REST ApiEndpoint - POST", "")

}

Container_Boundary(shopping_cart_, "/shopping_cart/") {
Component(shopping_cart__get, "getShoppingCart", "REST ApiEndpoint - GET", "")

}

Container_Boundary(shopping_cart_remove_item, "/shopping_cart/remove_item") {
Component(shopping_cart_remove_item_post, "removeItem", "REST ApiEndpoint - POST", "")

}

Container_Boundary(shopping_cart_update_quantity, "/shopping_cart/update_quantity") {
Component(shopping_cart_update_quantity_post, "updateQuantity", "REST ApiEndpoint - POST", "")

}



@enduml