@startuml OpenApi diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!theme blueprint
title Taxonomy API v1.0.0
footer OpenApi diagram - futurum.openapi-to-plantuml
Container_Boundary(category_tree_category_tree_id_fetch_item_aspects, "/category_tree/{category_tree_id}/fetch_item_aspects") {
Component(category_tree_category_tree_id_fetch_item_aspects_get, "Get Aspects for All Leaf Categories in a Marketplace\r[fetchItemAspects]", "REST ApiEndpoint - GET", "")

}

Container_Boundary(get_default_category_tree_id, "/get_default_category_tree_id") {
Component(get_default_category_tree_id_get, "Get a Default Category Tree ID\r[getDefaultCategoryTreeId]", "REST ApiEndpoint - GET", "")

}

Container_Boundary(category_tree_category_tree_id, "/category_tree/{category_tree_id}") {
Component(category_tree_category_tree_id_get, "Get a Category Tree\r[getCategoryTree]", "REST ApiEndpoint - GET", "")

}

Container_Boundary(category_tree_category_tree_id_get_category_subtree, "/category_tree/{category_tree_id}/get_category_subtree") {
Component(category_tree_category_tree_id_get_category_subtree_get, "Get a Category Subtree\r[getCategorySubtree]", "REST ApiEndpoint - GET", "")

}

Container_Boundary(category_tree_category_tree_id_get_category_suggestions, "/category_tree/{category_tree_id}/get_category_suggestions") {
Component(category_tree_category_tree_id_get_category_suggestions_get, "Get Suggested Categories\r[getCategorySuggestions]", "REST ApiEndpoint - GET", "")

}

Container_Boundary(category_tree_category_tree_id_get_item_aspects_for_category, "/category_tree/{category_tree_id}/get_item_aspects_for_category") {
Component(category_tree_category_tree_id_get_item_aspects_for_category_get, "getItemAspectsForCategory", "REST ApiEndpoint - GET", "")

}

Container_Boundary(category_tree_category_tree_id_get_compatibility_properties, "/category_tree/{category_tree_id}/get_compatibility_properties") {
Component(category_tree_category_tree_id_get_compatibility_properties_get, "Get Compatibility Properties\r[getCompatibilityProperties]", "REST ApiEndpoint - GET", "")

}

Container_Boundary(category_tree_category_tree_id_get_compatibility_property_values, "/category_tree/{category_tree_id}/get_compatibility_property_values") {
Component(category_tree_category_tree_id_get_compatibility_property_values_get, "Get Compatibility Property Values\r[getCompatibilityPropertyValues]", "REST ApiEndpoint - GET", "")

}



@enduml