@startuml OpenApi Type diagram

hide <<Path>> circle
hide <<Response>> circle
hide <<Parameter>> circle
hide empty methods
hide empty fields
set namespaceSeparator none

!theme blueprint
title Browse API v1.16.0
footer OpenApi Type diagram - futurum.openapi-to-plantuml
class "GET /item_summary/search" <<Path>> {
{field} aspect_filter : string {O}
{field} auto_correct : string {O}
{field} category_ids : string {O}
{field} charity_ids : string {O}
{field} compatibility_filter : string {O}
{field} epid : string {O}
{field} fieldgroups : string {O}
{field} filter : string {O}
{field} gtin : string {O}
{field} limit : string {O}
{field} offset : string {O}
{field} q : string {O}
{field} sort : string {O}
}

class "GET /item_summary/search 200" <<Response>> { }
class "GET /item_summary/search 400" <<Response>> { }
class "GET /item_summary/search 409" <<Response>> { }
class "GET /item_summary/search 500" <<Response>> { }
class "POST /item_summary/search_by_image" <<Path>> {
{field} aspect_filter : string {O}
{field} category_ids : string {O}
{field} charity_ids : string {O}
{field} fieldgroups : string {O}
{field} filter : string {O}
{field} limit : string {O}
{field} offset : string {O}
{field} sort : string {O}
}

class "POST /item_summary/search_by_image 200" <<Response>> { }
class "POST /item_summary/search_by_image 400" <<Response>> { }
class "POST /item_summary/search_by_image 409" <<Response>> { }
class "POST /item_summary/search_by_image 500" <<Response>> { }
class "GET /item/{item_id}" <<Path>> {
{field} fieldgroups : string {O}
{field} item_id : string
}

class "GET /item/{item_id} 200" <<Response>> { }
class "GET /item/{item_id} 400" <<Response>> { }
class "GET /item/{item_id} 404" <<Response>> { }
class "GET /item/{item_id} 409" <<Response>> { }
class "GET /item/{item_id} 500" <<Response>> { }
class "GET /item/get_item_by_legacy_id" <<Path>> {
{field} fieldgroups : string {O}
{field} legacy_item_id : string
{field} legacy_variation_id : string {O}
{field} legacy_variation_sku : string {O}
}

class "GET /item/get_item_by_legacy_id 200" <<Response>> { }
class "GET /item/get_item_by_legacy_id 400" <<Response>> { }
class "GET /item/get_item_by_legacy_id 404" <<Response>> { }
class "GET /item/get_item_by_legacy_id 409" <<Response>> { }
class "GET /item/get_item_by_legacy_id 500" <<Response>> { }
class "GET /item/" <<Path>> {
{field} item_ids : string {O}
{field} item_group_ids : string {O}
}

class "GET /item/ 200" <<Response>> { }
class "GET /item/ 400" <<Response>> { }
class "GET /item/ 404" <<Response>> { }
class "GET /item/ 409" <<Response>> { }
class "GET /item/ 500" <<Response>> { }
class "GET /item/get_items_by_item_group" <<Path>> {
{field} item_group_id : string
}

class "GET /item/get_items_by_item_group 200" <<Response>> { }
class "GET /item/get_items_by_item_group 400" <<Response>> { }
class "GET /item/get_items_by_item_group 404" <<Response>> { }
class "GET /item/get_items_by_item_group 409" <<Response>> { }
class "GET /item/get_items_by_item_group 500" <<Response>> { }
class "POST /item/{item_id}/check_compatibility" <<Path>> {
{field} item_id : string
{field} X-EBAY-C-MARKETPLACE-ID : string
}

class "POST /item/{item_id}/check_compatibility 200" <<Response>> { }
class "POST /item/{item_id}/check_compatibility 400" <<Response>> { }
class "POST /item/{item_id}/check_compatibility 404" <<Response>> { }
class "POST /item/{item_id}/check_compatibility 409" <<Response>> { }
class "POST /item/{item_id}/check_compatibility 500" <<Response>> { }
class "POST /shopping_cart/add_item" <<Path>> {
}

class "POST /shopping_cart/add_item 200" <<Response>> { }
class "POST /shopping_cart/add_item 204" <<Response>> { }
class "POST /shopping_cart/add_item 400" <<Response>> { }
class "POST /shopping_cart/add_item 403" <<Response>> { }
class "POST /shopping_cart/add_item 409" <<Response>> { }
class "POST /shopping_cart/add_item 500" <<Response>> { }
class "GET /shopping_cart/" <<Path>> {
}

class "GET /shopping_cart/ 200" <<Response>> { }
class "GET /shopping_cart/ 204" <<Response>> { }
class "GET /shopping_cart/ 400" <<Response>> { }
class "GET /shopping_cart/ 403" <<Response>> { }
class "GET /shopping_cart/ 404" <<Response>> { }
class "GET /shopping_cart/ 500" <<Response>> { }
class "POST /shopping_cart/remove_item" <<Path>> {
}

class "POST /shopping_cart/remove_item 200" <<Response>> { }
class "POST /shopping_cart/remove_item 204" <<Response>> { }
class "POST /shopping_cart/remove_item 400" <<Response>> { }
class "POST /shopping_cart/remove_item 403" <<Response>> { }
class "POST /shopping_cart/remove_item 409" <<Response>> { }
class "POST /shopping_cart/remove_item 500" <<Response>> { }
class "POST /shopping_cart/update_quantity" <<Path>> {
}

class "POST /shopping_cart/update_quantity 200" <<Response>> { }
class "POST /shopping_cart/update_quantity 400" <<Response>> { }
class "POST /shopping_cart/update_quantity 403" <<Response>> { }
class "POST /shopping_cart/update_quantity 409" <<Response>> { }
class "POST /shopping_cart/update_quantity 500" <<Response>> { }
class "AddCartItemInput" {
{field} itemId : string
{field} quantity : integer
}

class "AdditionalProductIdentity" {
{field} productIdentity : array<ProductIdentity>
}

class "AddonService" {
{field} selection : string
{field} serviceFee : 
{field} serviceId : string
{field} serviceType : string
}

class "Address" {
{field} addressLine1 : string
{field} addressLine2 : string
{field} city : string
{field} country : string
{field} county : string
{field} postalCode : string
{field} stateOrProvince : string
}

class "Amount" {
{field} currency : string
{field} value : string
}

class "Aspect" {
{field} localizedName : string
{field} localizedValues : array<string>
}

class "AspectDistribution" {
{field} aspectValueDistributions : array<AspectValueDistribution>
{field} localizedAspectName : string
}

class "AspectGroup" {
{field} aspects : array<Aspect>
{field} localizedGroupName : string
}

class "AspectValueDistribution" {
{field} localizedAspectValue : string
{field} matchCount : integer
{field} refinementHref : string
}

class "AttributeNameValue" {
{field} name : string
{field} value : string
}

class "AuthenticityGuaranteeProgram" {
{field} description : string
{field} termsWebUrl : string
}

class "AuthenticityVerificationProgram" {
{field} description : string
{field} termsWebUrl : string
}

class "AutoCorrections" {
{field} q : string
}

class "AvailableCoupon" {
{field} constraint : 
{field} discountAmount : 
{field} discountType : string
{field} message : string
{field} redemptionCode : string
{field} termsWebUrl : string
}

class "BuyingOptionDistribution" {
{field} buyingOption : string
{field} matchCount : integer
{field} refinementHref : string
}

class "CartItem" {
{field} cartItemId : string
{field} cartItemSubtotal : 
{field} image : 
{field} itemId : string
{field} itemWebUrl : string
{field} price : 
{field} quantity : integer
{field} title : string
}

class "Category" {
{field} categoryId : string
}

class "CategoryDistribution" {
{field} categoryId : string
{field} categoryName : string
{field} matchCount : integer
{field} refinementHref : string
}

class "CommonDescriptions" {
{field} description : string
{field} itemIds : array<string>
}

class "CompatibilityPayload" {
{field} compatibilityProperties : array<AttributeNameValue>
}

class "CompatibilityProperty" {
{field} localizedName : string
{field} name : string
{field} value : string
}

class "CompatibilityResponse" {
{field} compatibilityStatus : string
{field} warnings : array<Error>
}

class "ConditionDistribution" {
{field} condition : string
{field} conditionId : string
{field} matchCount : integer
{field} refinementHref : string
}

class "ConvertedAmount" {
{field} convertedFromCurrency : string
{field} convertedFromValue : string
{field} currency : string
{field} value : string
}

class "CoreItem" {
{field} additionalImages : array<Image>
{field} adultOnly : boolean
{field} ageGroup : string
{field} authenticityGuarantee : 
{field} authenticityVerification : 
{field} availableCoupons : array<AvailableCoupon>
{field} bidCount : integer
{field} brand : string
{field} buyingOptions : array<string>
{field} categoryId : string
{field} categoryPath : string
{field} color : string
{field} condition : string
{field} conditionDescription : string
{field} conditionId : string
{field} currentBidPrice : 
{field} description : string
{field} eligibleForInlineCheckout : boolean
{field} enabledForGuestCheckout : boolean
{field} energyEfficiencyClass : string
{field} epid : string
{field} estimatedAvailabilities : array<EstimatedAvailability>
{field} gender : string
{field} gtin : string
{field} image : 
{field} inferredEpid : string
{field} itemAffiliateWebUrl : string
{field} itemCreationDate : string
{field} itemEndDate : string
{field} itemId : string
{field} itemLocation : 
{field} itemWebUrl : string
{field} legacyItemId : string
{field} localizedAspects : array<TypedNameValue>
{field} lotSize : integer
{field} marketingPrice : 
{field} material : string
{field} minimumPriceToBid : 
{field} mpn : string
{field} pattern : string
{field} paymentMethods : array<PaymentMethod>
{field} price : 
{field} priceDisplayCondition : string
{field} primaryItemGroup : 
{field} primaryProductReviewRating : 
{field} priorityListing : boolean
{field} product : 
{field} productFicheWebUrl : string
{field} qualifiedPrograms : array<string>
{field} quantityLimitPerBuyer : integer
{field} reservePriceMet : boolean
{field} returnTerms : 
{field} seller : 
{field} sellerItemRevision : string
{field} shippingOptions : array<ShippingOption>
{field} shipToLocations : 
{field} shortDescription : string
{field} size : string
{field} sizeSystem : string
{field} sizeType : string
{field} subtitle : string
{field} taxes : array<Taxes>
{field} title : string
{field} topRatedBuyingExperience : boolean
{field} tyreLabelImageUrl : string
{field} uniqueBidderCount : integer
{field} unitPrice : 
{field} unitPricingMeasure : string
}

class "CouponConstraint" {
{field} expirationDate : string
}

class "Error" {
{field} category : string
{field} domain : string
{field} errorId : integer
{field} inputRefIds : array<string>
{field} longMessage : string
{field} message : string
{field} outputRefIds : array<string>
{field} parameters : array<ErrorParameter>
{field} subdomain : string
}

class "ErrorParameter" {
{field} name : string
{field} value : string
}

class "EstimatedAvailability" {
{field} availabilityThreshold : integer
{field} availabilityThresholdType : string
{field} deliveryOptions : array<string>
{field} estimatedAvailabilityStatus : string
{field} estimatedAvailableQuantity : integer
{field} estimatedSoldQuantity : integer
}

class "Image" {
{field} height : integer
{field} imageUrl : string
{field} width : integer
}

class "Item" {
{field} additionalImages : array<Image>
{field} addonServices : array<AddonService>
{field} adultOnly : boolean
{field} ageGroup : string
{field} authenticityGuarantee : 
{field} authenticityVerification : 
{field} availableCoupons : array<AvailableCoupon>
{field} bidCount : integer
{field} brand : string
{field} buyingOptions : array<string>
{field} categoryId : string
{field} categoryIdPath : string
{field} categoryPath : string
{field} color : string
{field} condition : string
{field} conditionDescription : string
{field} conditionId : string
{field} currentBidPrice : 
{field} description : string
{field} ecoParticipationFee : 
{field} eligibleForInlineCheckout : boolean
{field} enabledForGuestCheckout : boolean
{field} energyEfficiencyClass : string
{field} epid : string
{field} estimatedAvailabilities : array<EstimatedAvailability>
{field} gender : string
{field} gtin : string
{field} image : 
{field} inferredEpid : string
{field} itemAffiliateWebUrl : string
{field} itemCreationDate : string
{field} itemEndDate : string
{field} itemId : string
{field} itemLocation : 
{field} itemWebUrl : string
{field} legacyItemId : string
{field} listingMarketplaceId : string
{field} localizedAspects : array<TypedNameValue>
{field} lotSize : integer
{field} marketingPrice : 
{field} material : string
{field} minimumPriceToBid : 
{field} mpn : string
{field} pattern : string
{field} paymentMethods : array<PaymentMethod>
{field} price : 
{field} priceDisplayCondition : string
{field} primaryItemGroup : 
{field} primaryProductReviewRating : 
{field} priorityListing : boolean
{field} product : 
{field} productFicheWebUrl : string
{field} qualifiedPrograms : array<string>
{field} quantityLimitPerBuyer : integer
{field} reservePriceMet : boolean
{field} returnTerms : 
{field} seller : 
{field} sellerCustomPolicies : array<SellerCustomPolicy>
{field} sellerItemRevision : string
{field} shippingOptions : array<ShippingOption>
{field} shipToLocations : 
{field} shortDescription : string
{field} size : string
{field} sizeSystem : string
{field} sizeType : string
{field} subtitle : string
{field} taxes : array<Taxes>
{field} title : string
{field} topRatedBuyingExperience : boolean
{field} tyreLabelImageUrl : string
{field} uniqueBidderCount : integer
{field} unitPrice : 
{field} unitPricingMeasure : string
{field} warnings : array<Error>
{field} watchCount : integer
}

class "ItemGroup" {
{field} commonDescriptions : array<CommonDescriptions>
{field} items : array<Item>
{field} warnings : array<Error>
}

class "ItemGroupSummary" {
{field} itemGroupAdditionalImages : array<Image>
{field} itemGroupHref : string
{field} itemGroupId : string
{field} itemGroupImage : 
{field} itemGroupTitle : string
{field} itemGroupType : string
}

class "ItemLocationImpl" {
{field} addressLine1 : string
{field} addressLine2 : string
{field} city : string
{field} country : string
{field} county : string
{field} postalCode : string
{field} stateOrProvince : string
}

class "ItemReturnTerms" {
{field} extendedHolidayReturnsOffered : boolean
{field} refundMethod : string
{field} restockingFeePercentage : string
{field} returnInstructions : string
{field} returnMethod : string
{field} returnPeriod : 
{field} returnsAccepted : boolean
{field} returnShippingCostPayer : string
}

class "ItemSummary" {
{field} additionalImages : array<Image>
{field} adultOnly : boolean
{field} availableCoupons : boolean
{field} bidCount : integer
{field} buyingOptions : array<string>
{field} categories : array<Category>
{field} compatibilityMatch : string
{field} compatibilityProperties : array<CompatibilityProperty>
{field} condition : string
{field} conditionId : string
{field} currentBidPrice : 
{field} distanceFromPickupLocation : 
{field} energyEfficiencyClass : string
{field} epid : string
{field} image : 
{field} itemAffiliateWebUrl : string
{field} itemCreationDate : string
{field} itemEndDate : string
{field} itemGroupHref : string
{field} itemGroupType : string
{field} itemHref : string
{field} itemId : string
{field} itemLocation : 
{field} itemWebUrl : string
{field} legacyItemId : string
{field} listingMarketplaceId : string
{field} marketingPrice : 
{field} pickupOptions : array<PickupOptionSummary>
{field} price : 
{field} priceDisplayCondition : string
{field} priorityListing : boolean
{field} qualifiedPrograms : array<string>
{field} seller : 
{field} shippingOptions : array<ShippingOptionSummary>
{field} shortDescription : string
{field} thumbnailImages : array<Image>
{field} title : string
{field} topRatedBuyingExperience : boolean
{field} tyreLabelImageUrl : string
{field} unitPrice : 
{field} unitPricingMeasure : string
{field} watchCount : integer
}

class "Items" {
{field} items : array<CoreItem>
{field} total : integer
{field} warnings : array<Error>
}

class "LegalAddress" {
{field} addressLine1 : string
{field} addressLine2 : string
{field} city : string
{field} country : string
{field} countryName : string
{field} county : string
{field} postalCode : string
{field} stateOrProvince : string
}

class "MarketingPrice" {
{field} discountAmount : 
{field} discountPercentage : string
{field} originalPrice : 
{field} priceTreatment : string
}

class "PaymentMethod" {
{field} paymentMethodType : string
{field} paymentMethodBrands : array<PaymentMethodBrand>
{field} paymentInstructions : array<string>
{field} sellerInstructions : array<string>
}

class "PaymentMethodBrand" {
{field} paymentMethodBrandType : string
{field} logoImage : 
}

class "PickupOptionSummary" {
{field} pickupLocationType : string
}

class "Price" {
{field} convertedFromCurrency : string
{field} convertedFromValue : string
{field} currency : string
{field} value : string
}

class "Product" {
{field} additionalImages : array<Image>
{field} additionalProductIdentities : array<AdditionalProductIdentity>
{field} aspectGroups : array<AspectGroup>
{field} brand : string
{field} description : string
{field} gtins : array<string>
{field} image : 
{field} mpns : array<string>
{field} title : string
}

class "ProductIdentity" {
{field} identifierType : string
{field} identifierValue : string
}

class "RatingHistogram" {
{field} count : integer
{field} rating : string
}

class "Refinement" {
{field} aspectDistributions : array<AspectDistribution>
{field} buyingOptionDistributions : array<BuyingOptionDistribution>
{field} categoryDistributions : array<CategoryDistribution>
{field} conditionDistributions : array<ConditionDistribution>
{field} dominantCategoryId : string
}

class "Region" {
{field} regionName : string
{field} regionType : string
}

class "RemoteShopcartResponse" {
{field} cartItems : array<CartItem>
{field} cartSubtotal : 
{field} cartWebUrl : string
{field} unavailableCartItems : array<CartItem>
{field} warnings : array<Error>
}

class "RemoveCartItemInput" {
{field} cartItemId : string
}

class "ReviewRating" {
{field} averageRating : string
{field} ratingHistograms : array<RatingHistogram>
{field} reviewCount : integer
}

class "SearchByImageRequest" {
{field} image : string
}

class "SearchPagedCollection" {
{field} autoCorrections : 
{field} href : string
{field} itemSummaries : array<ItemSummary>
{field} limit : integer
{field} next : string
{field} offset : integer
{field} prev : string
{field} refinement : 
{field} total : integer
{field} warnings : array<Error>
}

class "Seller" {
{field} feedbackPercentage : string
{field} feedbackScore : integer
{field} sellerAccountType : string
{field} username : string
}

class "SellerCustomPolicy" {
{field} description : string
{field} label : string
{field} type : string
}

class "SellerDetail" {
{field} feedbackPercentage : string
{field} feedbackScore : integer
{field} sellerAccountType : string
{field} sellerLegalInfo : 
{field} username : string
}

class "SellerLegalInfo" {
{field} email : string
{field} fax : string
{field} imprint : string
{field} legalContactFirstName : string
{field} legalContactLastName : string
{field} name : string
{field} phone : string
{field} registrationNumber : string
{field} sellerProvidedLegalAddress : 
{field} termsOfService : string
{field} vatDetails : array<VatDetail>
}

class "ShipToLocation" {
{field} country : string
{field} postalCode : string
}

class "ShipToLocations" {
{field} regionExcluded : array<ShipToRegion>
{field} regionIncluded : array<ShipToRegion>
}

class "ShipToRegion" {
{field} regionId : string
{field} regionName : string
{field} regionType : string
}

class "ShippingOption" {
{field} additionalShippingCostPerUnit : 
{field} cutOffDateUsedForEstimate : string
{field} fulfilledThrough : string
{field} guaranteedDelivery : boolean
{field} importCharges : 
{field} maxEstimatedDeliveryDate : string
{field} minEstimatedDeliveryDate : string
{field} quantityUsedForEstimate : integer
{field} shippingCarrierCode : string
{field} shippingCost : 
{field} shippingCostType : string
{field} shippingServiceCode : string
{field} shipToLocationUsedForEstimate : 
{field} trademarkSymbol : string
{field} type : string
}

class "ShippingOptionSummary" {
{field} guaranteedDelivery : boolean
{field} maxEstimatedDeliveryDate : string
{field} minEstimatedDeliveryDate : string
{field} shippingCost : 
{field} shippingCostType : string
}

class "TargetLocation" {
{field} unitOfMeasure : string
{field} value : string
}

class "TaxJurisdiction" {
{field} region : 
{field} taxJurisdictionId : string
}

class "Taxes" {
{field} ebayCollectAndRemitTax : boolean
{field} includedInPrice : boolean
{field} shippingAndHandlingTaxed : boolean
{field} taxJurisdiction : 
{field} taxPercentage : string
{field} taxType : string
}

class "TimeDuration" {
{field} unit : string
{field} value : integer
}

class "TypedNameValue" {
{field} name : string
{field} type : string
{field} value : string
}

class "UpdateCartItemInput" {
{field} cartItemId : string
{field} quantity : integer
}

class "VatDetail" {
{field} issuingCountry : string
{field} vatId : string
}

"GET /item_summary/search" ..> "1" "GET /item_summary/search 200" : "200"
"GET /item_summary/search 200" ..> "1" "SearchPagedCollection"
"GET /item_summary/search" ..> "1" "GET /item_summary/search 400" : "400"
"GET /item_summary/search" ..> "1" "GET /item_summary/search 409" : "409"
"GET /item_summary/search" ..> "1" "GET /item_summary/search 500" : "500"
"POST /item_summary/search_by_image" ..> "1" "POST /item_summary/search_by_image 200" : "200"
"POST /item_summary/search_by_image 200" ..> "1" "SearchPagedCollection"
"POST /item_summary/search_by_image" ..> "1" "POST /item_summary/search_by_image 400" : "400"
"POST /item_summary/search_by_image" ..> "1" "POST /item_summary/search_by_image 409" : "409"
"POST /item_summary/search_by_image" ..> "1" "POST /item_summary/search_by_image 500" : "500"
"GET /item/{item_id}" ..> "1" "GET /item/{item_id} 200" : "200"
"GET /item/{item_id} 200" ..> "1" "Item"
"GET /item/{item_id}" ..> "1" "GET /item/{item_id} 400" : "400"
"GET /item/{item_id}" ..> "1" "GET /item/{item_id} 404" : "404"
"GET /item/{item_id}" ..> "1" "GET /item/{item_id} 409" : "409"
"GET /item/{item_id}" ..> "1" "GET /item/{item_id} 500" : "500"
"GET /item/get_item_by_legacy_id" ..> "1" "GET /item/get_item_by_legacy_id 200" : "200"
"GET /item/get_item_by_legacy_id 200" ..> "1" "Item"
"GET /item/get_item_by_legacy_id" ..> "1" "GET /item/get_item_by_legacy_id 400" : "400"
"GET /item/get_item_by_legacy_id" ..> "1" "GET /item/get_item_by_legacy_id 404" : "404"
"GET /item/get_item_by_legacy_id" ..> "1" "GET /item/get_item_by_legacy_id 409" : "409"
"GET /item/get_item_by_legacy_id" ..> "1" "GET /item/get_item_by_legacy_id 500" : "500"
"GET /item/" ..> "1" "GET /item/ 200" : "200"
"GET /item/ 200" ..> "1" "Items"
"GET /item/" ..> "1" "GET /item/ 400" : "400"
"GET /item/" ..> "1" "GET /item/ 404" : "404"
"GET /item/" ..> "1" "GET /item/ 409" : "409"
"GET /item/" ..> "1" "GET /item/ 500" : "500"
"GET /item/get_items_by_item_group" ..> "1" "GET /item/get_items_by_item_group 200" : "200"
"GET /item/get_items_by_item_group 200" ..> "1" "ItemGroup"
"GET /item/get_items_by_item_group" ..> "1" "GET /item/get_items_by_item_group 400" : "400"
"GET /item/get_items_by_item_group" ..> "1" "GET /item/get_items_by_item_group 404" : "404"
"GET /item/get_items_by_item_group" ..> "1" "GET /item/get_items_by_item_group 409" : "409"
"GET /item/get_items_by_item_group" ..> "1" "GET /item/get_items_by_item_group 500" : "500"
"POST /item/{item_id}/check_compatibility" ..> "1" "POST /item/{item_id}/check_compatibility 200" : "200"
"POST /item/{item_id}/check_compatibility 200" ..> "1" "CompatibilityResponse"
"POST /item/{item_id}/check_compatibility" ..> "1" "POST /item/{item_id}/check_compatibility 400" : "400"
"POST /item/{item_id}/check_compatibility" ..> "1" "POST /item/{item_id}/check_compatibility 404" : "404"
"POST /item/{item_id}/check_compatibility" ..> "1" "POST /item/{item_id}/check_compatibility 409" : "409"
"POST /item/{item_id}/check_compatibility" ..> "1" "POST /item/{item_id}/check_compatibility 500" : "500"
"POST /shopping_cart/add_item" ..> "1" "POST /shopping_cart/add_item 200" : "200"
"POST /shopping_cart/add_item 200" ..> "1" "RemoteShopcartResponse"
"POST /shopping_cart/add_item" ..> "1" "POST /shopping_cart/add_item 204" : "204"
"POST /shopping_cart/add_item" ..> "1" "POST /shopping_cart/add_item 400" : "400"
"POST /shopping_cart/add_item" ..> "1" "POST /shopping_cart/add_item 403" : "403"
"POST /shopping_cart/add_item" ..> "1" "POST /shopping_cart/add_item 409" : "409"
"POST /shopping_cart/add_item" ..> "1" "POST /shopping_cart/add_item 500" : "500"
"GET /shopping_cart/" ..> "1" "GET /shopping_cart/ 200" : "200"
"GET /shopping_cart/ 200" ..> "1" "RemoteShopcartResponse"
"GET /shopping_cart/" ..> "1" "GET /shopping_cart/ 204" : "204"
"GET /shopping_cart/" ..> "1" "GET /shopping_cart/ 400" : "400"
"GET /shopping_cart/" ..> "1" "GET /shopping_cart/ 403" : "403"
"GET /shopping_cart/" ..> "1" "GET /shopping_cart/ 404" : "404"
"GET /shopping_cart/" ..> "1" "GET /shopping_cart/ 500" : "500"
"POST /shopping_cart/remove_item" ..> "1" "POST /shopping_cart/remove_item 200" : "200"
"POST /shopping_cart/remove_item 200" ..> "1" "RemoteShopcartResponse"
"POST /shopping_cart/remove_item" ..> "1" "POST /shopping_cart/remove_item 204" : "204"
"POST /shopping_cart/remove_item" ..> "1" "POST /shopping_cart/remove_item 400" : "400"
"POST /shopping_cart/remove_item" ..> "1" "POST /shopping_cart/remove_item 403" : "403"
"POST /shopping_cart/remove_item" ..> "1" "POST /shopping_cart/remove_item 409" : "409"
"POST /shopping_cart/remove_item" ..> "1" "POST /shopping_cart/remove_item 500" : "500"
"POST /shopping_cart/update_quantity" ..> "1" "POST /shopping_cart/update_quantity 200" : "200"
"POST /shopping_cart/update_quantity 200" ..> "1" "RemoteShopcartResponse"
"POST /shopping_cart/update_quantity" ..> "1" "POST /shopping_cart/update_quantity 400" : "400"
"POST /shopping_cart/update_quantity" ..> "1" "POST /shopping_cart/update_quantity 403" : "403"
"POST /shopping_cart/update_quantity" ..> "1" "POST /shopping_cart/update_quantity 409" : "409"
"POST /shopping_cart/update_quantity" ..> "1" "POST /shopping_cart/update_quantity 500" : "500"
"POST /item_summary/search_by_image" ..> "1" "SearchByImageRequest"
"POST /item/{item_id}/check_compatibility" ..> "1" "CompatibilityPayload"
"POST /shopping_cart/add_item" ..> "1" "AddCartItemInput"
"POST /shopping_cart/remove_item" ..> "1" "RemoveCartItemInput"
"POST /shopping_cart/update_quantity" ..> "1" "UpdateCartItemInput"


@enduml