@startuml OpenApi Type diagram

hide <<Path>> circle
hide <<Response>> circle
hide <<Parameter>> circle
hide empty methods
hide empty fields
set namespaceSeparator none

title Taxonomy API v1.0.0
footer OpenApi Type diagram - futurum.openapi-to-plantuml
class "GET /category_tree/{category_tree_id}/fetch_item_aspects" <<Path>> {
{field} category_tree_id : string
}

class "GET /category_tree/{category_tree_id}/fetch_item_aspects 200" <<Response>> { }
class "GET /category_tree/{category_tree_id}/fetch_item_aspects 400" <<Response>> { }
class "GET /category_tree/{category_tree_id}/fetch_item_aspects 404" <<Response>> { }
class "GET /category_tree/{category_tree_id}/fetch_item_aspects 500" <<Response>> { }
class "GET /get_default_category_tree_id" <<Path>> {
{field} Accept-Language : string {O}
{field} marketplace_id : string
}

class "GET /get_default_category_tree_id 200" <<Response>> { }
class "GET /get_default_category_tree_id 204" <<Response>> { }
class "GET /get_default_category_tree_id 400" <<Response>> { }
class "GET /get_default_category_tree_id 500" <<Response>> { }
class "GET /category_tree/{category_tree_id}" <<Path>> {
{field} category_tree_id : string
}

class "GET /category_tree/{category_tree_id} 200" <<Response>> { }
class "GET /category_tree/{category_tree_id} 400" <<Response>> { }
class "GET /category_tree/{category_tree_id} 404" <<Response>> { }
class "GET /category_tree/{category_tree_id} 500" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_category_subtree" <<Path>> {
{field} category_id : string
{field} category_tree_id : string
}

class "GET /category_tree/{category_tree_id}/get_category_subtree 200" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_category_subtree 400" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_category_subtree 404" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_category_subtree 500" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_category_suggestions" <<Path>> {
{field} category_tree_id : string
{field} q : string
}

class "GET /category_tree/{category_tree_id}/get_category_suggestions 200" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_category_suggestions 204" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_category_suggestions 400" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_category_suggestions 404" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_category_suggestions 500" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_item_aspects_for_category" <<Path>> {
{field} category_id : string
{field} category_tree_id : string
}

class "GET /category_tree/{category_tree_id}/get_item_aspects_for_category 200" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_item_aspects_for_category 204" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_item_aspects_for_category 400" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_item_aspects_for_category 404" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_item_aspects_for_category 500" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_compatibility_properties" <<Path>> {
{field} category_tree_id : string
{field} category_id : string
}

class "GET /category_tree/{category_tree_id}/get_compatibility_properties 200" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_compatibility_properties 204" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_compatibility_properties 400" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_compatibility_properties 404" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_compatibility_properties 500" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_compatibility_property_values" <<Path>> {
{field} category_tree_id : string
{field} compatibility_property : string
{field} category_id : string
{field} filter : string {O}
}

class "GET /category_tree/{category_tree_id}/get_compatibility_property_values 200" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_compatibility_property_values 204" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_compatibility_property_values 400" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_compatibility_property_values 404" <<Response>> { }
class "GET /category_tree/{category_tree_id}/get_compatibility_property_values 500" <<Response>> { }
class "AncestorReference" {
{field} categoryId : string
{field} categoryName : string
{field} categorySubtreeNodeHref : string
{field} categoryTreeNodeLevel : integer
}

class "Aspect" {
{field} aspectConstraint : 
{field} aspectValues : array<AspectValue>
{field} localizedAspectName : string
{field} relevanceIndicator : 
}

class "AspectConstraint" {
{field} aspectApplicableTo : array<string>
{field} aspectDataType : string
{field} aspectEnabledForVariations : boolean
{field} aspectFormat : string
{field} aspectMaxLength : integer
{field} aspectMode : string
{field} aspectRequired : boolean
{field} aspectUsage : string
{field} expectedRequiredByDate : string
{field} itemToAspectCardinality : string
}

class "AspectMetadata" {
{field} aspects : array<Aspect>
}

class "AspectValue" {
{field} localizedValue : string
{field} valueConstraints : array<ValueConstraint>
}

class "BaseCategoryTree" {
{field} categoryTreeId : string
{field} categoryTreeVersion : string
}

class "Category" {
{field} categoryId : string
{field} categoryName : string
}

class "CategoryAspect" {
{field} category : 
{field} aspects : array<Aspect>
}

class "CategorySubtree" {
{field} categorySubtreeNode : 
{field} categoryTreeId : string
{field} categoryTreeVersion : string
}

class "CategorySuggestion" {
{field} category : 
{field} categoryTreeNodeAncestors : array<AncestorReference>
{field} categoryTreeNodeLevel : integer
{field} relevancy : string
}

class "CategorySuggestionResponse" {
{field} categorySuggestions : array<CategorySuggestion>
{field} categoryTreeId : string
{field} categoryTreeVersion : string
}

class "CategoryTree" {
{field} applicableMarketplaceIds : array<string>
{field} categoryTreeId : string
{field} categoryTreeVersion : string
{field} rootCategoryNode : 
}

class "CategoryTreeNode" {
{field} category : 
{field} categoryTreeNodeLevel : integer
{field} childCategoryTreeNodes : array<CategoryTreeNode>
{field} leafCategoryTreeNode : boolean
{field} parentCategoryTreeNodeHref : string
}

class "CompatibilityProperty" {
{field} name : string
{field} localizedName : string
}

class "CompatibilityPropertyValue" {
{field} value : string
}

class "Error" {
{field} category : string
{field} domain : string
{field} errorId : integer
{field} inputRefIds : array<string>
{field} longMessage : string
{field} message : string
{field} outputRefIds : array<string>
{field} parameters : array<ErrorParameter>
{field} subdomain : string
}

class "ErrorParameter" {
{field} name : string
{field} value : string
}

class "GetCategoriesAspectResponse" {
{field} categoryTreeId : string
{field} categoryTreeVersion : string
{field} categoryAspects : array<CategoryAspect>
}

class "GetCompatibilityMetadataResponse" {
{field} compatibilityProperties : array<CompatibilityProperty>
}

class "GetCompatibilityPropertyValuesResponse" {
{field} compatibilityPropertyValues : array<CompatibilityPropertyValue>
}

class "RelevanceIndicator" {
{field} searchCount : integer
}

class "ValueConstraint" {
{field} applicableForLocalizedAspectName : string
{field} applicableForLocalizedAspectValues : array<string>
}

"GET /category_tree/{category_tree_id}/fetch_item_aspects" ..> "1" "GET /category_tree/{category_tree_id}/fetch_item_aspects 200" : "200"
"GET /category_tree/{category_tree_id}/fetch_item_aspects 200" ..> "1" "GetCategoriesAspectResponse"
"GET /category_tree/{category_tree_id}/fetch_item_aspects" ..> "1" "GET /category_tree/{category_tree_id}/fetch_item_aspects 400" : "400"
"GET /category_tree/{category_tree_id}/fetch_item_aspects" ..> "1" "GET /category_tree/{category_tree_id}/fetch_item_aspects 404" : "404"
"GET /category_tree/{category_tree_id}/fetch_item_aspects" ..> "1" "GET /category_tree/{category_tree_id}/fetch_item_aspects 500" : "500"
"GET /get_default_category_tree_id" ..> "1" "GET /get_default_category_tree_id 200" : "200"
"GET /get_default_category_tree_id 200" ..> "1" "BaseCategoryTree"
"GET /get_default_category_tree_id" ..> "1" "GET /get_default_category_tree_id 204" : "204"
"GET /get_default_category_tree_id" ..> "1" "GET /get_default_category_tree_id 400" : "400"
"GET /get_default_category_tree_id" ..> "1" "GET /get_default_category_tree_id 500" : "500"
"GET /category_tree/{category_tree_id}" ..> "1" "GET /category_tree/{category_tree_id} 200" : "200"
"GET /category_tree/{category_tree_id} 200" ..> "1" "CategoryTree"
"GET /category_tree/{category_tree_id}" ..> "1" "GET /category_tree/{category_tree_id} 400" : "400"
"GET /category_tree/{category_tree_id}" ..> "1" "GET /category_tree/{category_tree_id} 404" : "404"
"GET /category_tree/{category_tree_id}" ..> "1" "GET /category_tree/{category_tree_id} 500" : "500"
"GET /category_tree/{category_tree_id}/get_category_subtree" ..> "1" "GET /category_tree/{category_tree_id}/get_category_subtree 200" : "200"
"GET /category_tree/{category_tree_id}/get_category_subtree 200" ..> "1" "CategorySubtree"
"GET /category_tree/{category_tree_id}/get_category_subtree" ..> "1" "GET /category_tree/{category_tree_id}/get_category_subtree 400" : "400"
"GET /category_tree/{category_tree_id}/get_category_subtree" ..> "1" "GET /category_tree/{category_tree_id}/get_category_subtree 404" : "404"
"GET /category_tree/{category_tree_id}/get_category_subtree" ..> "1" "GET /category_tree/{category_tree_id}/get_category_subtree 500" : "500"
"GET /category_tree/{category_tree_id}/get_category_suggestions" ..> "1" "GET /category_tree/{category_tree_id}/get_category_suggestions 200" : "200"
"GET /category_tree/{category_tree_id}/get_category_suggestions 200" ..> "1" "CategorySuggestionResponse"
"GET /category_tree/{category_tree_id}/get_category_suggestions" ..> "1" "GET /category_tree/{category_tree_id}/get_category_suggestions 204" : "204"
"GET /category_tree/{category_tree_id}/get_category_suggestions" ..> "1" "GET /category_tree/{category_tree_id}/get_category_suggestions 400" : "400"
"GET /category_tree/{category_tree_id}/get_category_suggestions" ..> "1" "GET /category_tree/{category_tree_id}/get_category_suggestions 404" : "404"
"GET /category_tree/{category_tree_id}/get_category_suggestions" ..> "1" "GET /category_tree/{category_tree_id}/get_category_suggestions 500" : "500"
"GET /category_tree/{category_tree_id}/get_item_aspects_for_category" ..> "1" "GET /category_tree/{category_tree_id}/get_item_aspects_for_category 200" : "200"
"GET /category_tree/{category_tree_id}/get_item_aspects_for_category 200" ..> "1" "AspectMetadata"
"GET /category_tree/{category_tree_id}/get_item_aspects_for_category" ..> "1" "GET /category_tree/{category_tree_id}/get_item_aspects_for_category 204" : "204"
"GET /category_tree/{category_tree_id}/get_item_aspects_for_category" ..> "1" "GET /category_tree/{category_tree_id}/get_item_aspects_for_category 400" : "400"
"GET /category_tree/{category_tree_id}/get_item_aspects_for_category" ..> "1" "GET /category_tree/{category_tree_id}/get_item_aspects_for_category 404" : "404"
"GET /category_tree/{category_tree_id}/get_item_aspects_for_category" ..> "1" "GET /category_tree/{category_tree_id}/get_item_aspects_for_category 500" : "500"
"GET /category_tree/{category_tree_id}/get_compatibility_properties" ..> "1" "GET /category_tree/{category_tree_id}/get_compatibility_properties 200" : "200"
"GET /category_tree/{category_tree_id}/get_compatibility_properties 200" ..> "1" "GetCompatibilityMetadataResponse"
"GET /category_tree/{category_tree_id}/get_compatibility_properties" ..> "1" "GET /category_tree/{category_tree_id}/get_compatibility_properties 204" : "204"
"GET /category_tree/{category_tree_id}/get_compatibility_properties" ..> "1" "GET /category_tree/{category_tree_id}/get_compatibility_properties 400" : "400"
"GET /category_tree/{category_tree_id}/get_compatibility_properties" ..> "1" "GET /category_tree/{category_tree_id}/get_compatibility_properties 404" : "404"
"GET /category_tree/{category_tree_id}/get_compatibility_properties" ..> "1" "GET /category_tree/{category_tree_id}/get_compatibility_properties 500" : "500"
"GET /category_tree/{category_tree_id}/get_compatibility_property_values" ..> "1" "GET /category_tree/{category_tree_id}/get_compatibility_property_values 200" : "200"
"GET /category_tree/{category_tree_id}/get_compatibility_property_values 200" ..> "1" "GetCompatibilityPropertyValuesResponse"
"GET /category_tree/{category_tree_id}/get_compatibility_property_values" ..> "1" "GET /category_tree/{category_tree_id}/get_compatibility_property_values 204" : "204"
"GET /category_tree/{category_tree_id}/get_compatibility_property_values" ..> "1" "GET /category_tree/{category_tree_id}/get_compatibility_property_values 400" : "400"
"GET /category_tree/{category_tree_id}/get_compatibility_property_values" ..> "1" "GET /category_tree/{category_tree_id}/get_compatibility_property_values 404" : "404"
"GET /category_tree/{category_tree_id}/get_compatibility_property_values" ..> "1" "GET /category_tree/{category_tree_id}/get_compatibility_property_values 500" : "500"


@enduml