@startuml OpenApi diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Swagger Petstore v1.0.6
footer OpenApi diagram - futurum.openapi-to-plantuml
Container_Boundary(pet_petId_uploadImage, "/pet/{petId}/uploadImage") {
Component(pet_petId_uploadImage_post, "uploads an image\r[uploadFile]", "REST ApiEndpoint - POST", "")

}

Container_Boundary(pet, "/pet") {
Component(pet_post, "Add a new pet to the store\r[addPet]", "REST ApiEndpoint - POST", "")

Component(pet_put, "Update an existing pet\r[updatePet]", "REST ApiEndpoint - PUT", "")

}

Container_Boundary(pet_findByStatus, "/pet/findByStatus") {
Component(pet_findByStatus_get, "Finds Pets by status\r[findPetsByStatus]", "REST ApiEndpoint - GET", "")

}

Container_Boundary(pet_findByTags, "/pet/findByTags") {
Component(pet_findByTags_get, "Finds Pets by tags\r[findPetsByTags]", "REST ApiEndpoint - GET", "")

}

Container_Boundary(pet_petId, "/pet/{petId}") {
Component(pet_petId_get, "Find pet by ID\r[getPetById]", "REST ApiEndpoint - GET", "")

Component(pet_petId_post, "Updates a pet in the store with form data\r[updatePetWithForm]", "REST ApiEndpoint - POST", "")

Component(pet_petId_delete, "Deletes a pet\r[deletePet]", "REST ApiEndpoint - DELETE", "")

}

Container_Boundary(store_order, "/store/order") {
Component(store_order_post, "Place an order for a pet\r[placeOrder]", "REST ApiEndpoint - POST", "")

}

Container_Boundary(store_order_orderId, "/store/order/{orderId}") {
Component(store_order_orderId_get, "Find purchase order by ID\r[getOrderById]", "REST ApiEndpoint - GET", "")

Component(store_order_orderId_delete, "Delete purchase order by ID\r[deleteOrder]", "REST ApiEndpoint - DELETE", "")

}

Container_Boundary(store_inventory, "/store/inventory") {
Component(store_inventory_get, "Returns pet inventories by status\r[getInventory]", "REST ApiEndpoint - GET", "")

}

Container_Boundary(user_createWithArray, "/user/createWithArray") {
Component(user_createWithArray_post, "Creates list of users with given input array\r[createUsersWithArrayInput]", "REST ApiEndpoint - POST", "")

}

Container_Boundary(user_createWithList, "/user/createWithList") {
Component(user_createWithList_post, "Creates list of users with given input array\r[createUsersWithListInput]", "REST ApiEndpoint - POST", "")

}

Container_Boundary(user_username, "/user/{username}") {
Component(user_username_get, "Get user by user name\r[getUserByName]", "REST ApiEndpoint - GET", "")

Component(user_username_put, "Updated user\r[updateUser]", "REST ApiEndpoint - PUT", "")

Component(user_username_delete, "Delete user\r[deleteUser]", "REST ApiEndpoint - DELETE", "")

}

Container_Boundary(user_login, "/user/login") {
Component(user_login_get, "Logs user into the system\r[loginUser]", "REST ApiEndpoint - GET", "")

}

Container_Boundary(user_logout, "/user/logout") {
Component(user_logout_get, "Logs out current logged in user session\r[logoutUser]", "REST ApiEndpoint - GET", "")

}

Container_Boundary(user, "/user") {
Component(user_post, "Create user\r[createUser]", "REST ApiEndpoint - POST", "")

}



@enduml