@startuml OpenApi diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Swagger Petstore v1.0.0
footer OpenApi diagram - futurum.openapi-to-plantuml
Container_Boundary(pets, "/pets") {
Component(pets_get, "List all pets\r[listPets]", "REST ApiEndpoint - GET", "")

Component(pets_post, "Create a pet\r[createPets]", "REST ApiEndpoint - POST", "")

}

Container_Boundary(pets_petId, "/pets/{petId}") {
Component(pets_petId_get, "Info for a specific pet\r[showPetById]", "REST ApiEndpoint - GET", "")

}



@enduml